### ISSUE TITLE
gaze allows $path - is that possible with chokidar too?

### ISSUE THREAD

**Issue by serapath** [kimmobrunfeldt/chokidar-cli#10]
`gaze "cpy $path build/assets" "assets/**/*"` using [cpy](https://github.com/sindresorhus/cpy)

**Comment by kimmobrunfeldt** [comment]
Environment variables should be available to the commands run with chokidar.

For example:

```
$ export VARIABLE=12341
$ chokidar test.txt -c "echo $VARIABLE"
Watching "test.txt" ..
change:test.txt
12341
```

**Comment by serapath** [comment]
True, but it seems `gaze` updates `$path` onfilechange before it runs the command given to it.

**Comment by kimmobrunfeldt** [comment]
Sorry I don't know the `gaze` command. What do you expect the `$path` variable to be?

**Comment by serapath** [comment]
so `gaze "cpy $path build/assets" "assets/**/*"` watches the `assets` folder and all subfolders for file changes. Whenever a file changes, the command `"cpy $path build/assets"` is executed and `$path` is the path to the changed file.

**Comment by kimmobrunfeldt** [comment]
There are two duplicate issues opened, let's continue discussion in this one: https://github.com/kimmobrunfeldt/chokidar-cli/issues/11
