### ISSUE TITLE
No way to customize the shell command to be executed

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/chokidar-cli#18]
Different platforms have different shells. The current detection only checks COMSPEC and SHELL environment variables to detect if we're on Windows or *nix.

This obviously doesn't work for everyone and it'd be nice to be able to customize how the underlying platform shell is called. 

For example a new flag:

```
--shell-command "cmd.exe /c {{command}}"
```

**Comment by heikkipora** [comment]
Looks like nobody wants this, closing.
