### ISSUE TITLE
can't install on linux machine

### ISSUE THREAD

**Issue by villesau** [kimmobrunfeldt/chokidar-cli#24]
npm install fails on linux machine with this library. This is pretty awkward since it breaks our build process:

17:03:54 npm ERR! Linux 3.13.0-66-generic
17:03:54 npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
17:03:54 npm ERR! node v0.12.9
17:03:54 npm ERR! npm  v2.14.9
17:03:54 npm ERR! code EBADPLATFORM
17:03:54 
17:03:54 npm ERR! notsup Unsupported
17:03:54 npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.7
17:03:54 npm ERR! notsup Valid OS:    darwin
17:03:54 npm ERR! notsup Valid Arch:  any
17:03:54 npm ERR! notsup Actual OS:   linux
17:03:54 npm ERR! notsup Actual Arch: x64
17:03:54 
17:03:54 npm ERR! Please include the following file with any support request:

**Comment by kimmobrunfeldt** [comment]
This sounds like an issue with some chokidar dependency. Have you checked chokidar issues? For example https://github.com/paulmillr/chokidar/issues/432

**Comment by villesau** [comment]
wow, super fast response time! :)

I think that's a different problem, or actually not a problem at all.. I'm not sure if the problem is related to our use of shrinkwrap. shrinkwrapping chokidar-cli in node modules seem to add the fsevents to npm-shrinkwrap like any other dependency. Quick googling didn't tell how npm shrinkwrap (with --dev) is supposed to deal with optional deps.

**Comment by kimmobrunfeldt** [comment]
Hehe, I was still having a few beers at the office and happened to notice your comment :)

Ok. When you get it solved, could you post the solution to this thread?

**Comment by es128** [comment]
It's an npm bug. More info and some potential workarounds discussed in https://github.com/npm/npm/issues/2679

**Comment by villesau** [comment]
Thanks @es128!
Solutions for the bug seems to be pretty hackish: https://github.com/npm/npm/issues/2679#issuecomment-150084700
https://github.com/bocoup/service-catalog/commit/7406d5c18fa9c7dcb32510c0878ed62796779ab6

This is an awkward problem from npm end.. So this is not related to chokidar or chokidar-cli after all but our npm shrinkwrap steup instead. Pretty annoying if we have to go with some hack to get the dep out of shrinkwrap, but apparently no can do. Once again an interesting lesson learned.

**Comment by kimmobrunfeldt** [comment]
Closing as this seemed to be unrelated to chokidar-cli module.
