### ISSUE TITLE
Possibility to set up multiple watchers each with a command

### ISSUE THREAD

**Issue by MarcDiethelm** [kimmobrunfeldt/chokidar-cli#26]
Is this possible? E.g. `npm run watch-js ; npm run watch-css`
Or should I use `concurrently` for this?

**Comment by kimmobrunfeldt** [comment]
I would recommend to run multiple chokidar-cli processes for this, so yeah e.g. with [concurrently](https://github.com/kimmobrunfeldt/concurrently). I think this is out of the library scope, as it is simpler to spawn multiple processes. If this is a popular use case, we can reconsider. Closing this for now.

**Comment by MarcDiethelm** [comment]
Cool, thanks for the reply,

**Comment by emmby** [comment]
I too would like this. I use chokidar in package.json to watch source for changes and to run testscases. I'd like to also add a standardjs formatting check.  Doing this would concurrently would require duplicating the entire chokidar command line, which is somewhat complex.  Being able to just add a second -c would be much more convenient.
