### ISSUE TITLE
--ignore switches has no effect

### ISSUE THREAD

**Issue by bonsoir** [kimmobrunfeldt/chokidar-cli#3]
Line 162 of index.js 
if (opts.ignore) chokidarOpts.ignore = opts.ignore;
->
if (opts.ignore) chokidarOpts.ignored = opts.ignore;

Making the above change seems did the job.
I'm not familiar with Node API so don't know for sure.
Could you take a look?

**Comment by kimmobrunfeldt** [comment]
Yeah it seemed that I used incorrect wording in the option. It's `ignored` as you said. Thanks for reporting. I fixed this now.

**Comment by kimmobrunfeldt** [comment]
Released in 0.2.1: https://github.com/kimmobrunfeldt/chokidar-cli/releases/tag/0.2.1
