### ISSUE TITLE
Option to turn off debounce/throttle

### ISSUE THREAD

**Issue by tlancina** [kimmobrunfeldt/chokidar-cli#37]
Even if you set a wait of 0, if there are multiple change events from fsevents in the same event loop, only one will have a command executed for it.

This is a problem when transpiling or generating sourcemaps, which can affect multiple files at a time.

**Comment by lossanarch** [comment]
This problem is fixed by PR#52 (https://github.com/kimmobrunfeldt/chokidar-cli/pull/52) which allows full avoidance of debounce.

**Comment by sbleon** [comment]
This is fixed by #90, which has been merged. I think this issue can be closed.
