### ISSUE TITLE
Using shell function as a command

### ISSUE THREAD

**Issue by lzrski** [kimmobrunfeldt/chokidar-cli#48]
Hey, thanks for chokidar. It's a very nice lightweight alternative to gulp and such.

I was hoping to use a bash function as a value to `--command` option, like that:

```sh
#! /usr/bin/env bash

# Start development loop - watch and rebuild, etc.

# Shell strict mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

function tasks {
  clear
  scripts/build
  scripts/test
}

export -f tasks

scripts/clean
chokidar \
  "src/**/*" \
  --initial \
  --command tasks
```

I know some workarounds (like in-lining the tasks and separating them with `&&` or just putting them in another script), but the code above makes a really nice, self contained unit. Any chance we can make this work?

**Comment by heikkipora** [comment]
I don't see/know of a way for chokidar to be able to execute a function like that. When chokidar  runs it cannot possibly have any way to access the function defined in that script.
The best way IMHO is to create a separate script out of that function (like you have discovered). Closing this issue.
