### ISSUE TITLE
How to restart a Express/Koa server?

### ISSUE THREAD

**Issue by corysimmons** [kimmobrunfeldt/chokidar-cli#49]
I'm trying to watch all my src files and rerun Koa when a file is changed, but keep hitting `Error: listen EADDRINUSE :::3000`.

`"chokidar": "chokidar '**/*.js' -c 'node dist/server'"`

Any ideas how to force Koa to die before running `node dist/server`?

**Comment by heikkipora** [comment]
I'm closing this as it's more of a Koa question than chokidar-cli (and besides, it's one year old..)

**Comment by corysimmons** [comment]
Not a Koa question. More of a question with killing child processes.

https://github.com/kimmobrunfeldt/chokidar-cli/pull/29 fixes it and should be reviewed/merged.

**Comment by zanona** [comment]
I believe this should be reopened and #29 given due attention?
By no means, this issue gives the impression to be a koa or express as @corysimmons mentioned.

**Comment by corysimmons** [comment]
https://www.npmjs.com/package/chokidar-cli-infanticide is just #29 merged and worked well for me.
