### ISSUE TITLE
--initial doesn't respect --ignore

### ISSUE THREAD

**Issue by btknorr** [kimmobrunfeldt/chokidar-cli#5]
For example:

```node_modules/chokidar-cli --ignore 'build' --ignore 'components' '**/*' --initial -c 'duo --use node_modules/duo-jade --copy --verbose index.js index.css'```

The duo 'command' creates folders and files in the components folder, and chokidar will run the 'command' over and over again because things changed in the components folder, even though it's ignored.

**Comment by kimmobrunfeldt** [comment]
I can't reproduce this with these tests:

* `node index.js --initial --ignore 'a' -c 'mkdir a' '*'`
* `node index.js --initial --ignore a.txt -c 'touch a.txt' '*'`

**Comment by kimmobrunfeldt** [comment]
I just released 0.3.0, can you try that version?

**Comment by kimmobrunfeldt** [comment]
Cloising because of inactivity.
