### ISSUE TITLE
Vulnerability found in npm audit

### ISSUE THREAD

**Issue by rodrigooler** [kimmobrunfeldt/chokidar-cli#55]
I'm using the latest version of npm that has the "audit" functionality that serves to find third-party passwords.

When executing the command the following information is displayed.

![captura de tela 2018-06-07 as 02 33 31](https://user-images.githubusercontent.com/5496931/41080107-36db56b6-69fb-11e8-97b8-28446fc00c0d.png)

When doing fork I get the following message when verifying the audit

found 6 vulnerabilities (3 low, 2 high, 1 critical) in 330 scanned packages
  4 vulnerabilities require semver-major dependency updates.
  2 vulnerabilities require manual review. See the full report for details.

When updating dependencies, the result of vulnerabilities found by npm audit are as follows.

![captura de tela 2018-06-07 as 02 48 46](https://user-images.githubusercontent.com/5496931/41080535-66148996-69fd-11e8-8d90-d7358c198201.png)
 

repo fork: https://github.com/rodrigooler/chokidar-cli/commits/master

**Comment by rodrigooler** [comment]
- [ ] string -> https://github.com/jprichardson/string.js/issues/212
- [ ] releasor -> https://github.com/kimmobrunfeldt/releasor

**Comment by heikkipora** [comment]
Latest release https://github.com/kimmobrunfeldt/chokidar-cli/releases/tag/1.2.1

```
$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 1312 scanned packages
```
