### ISSUE TITLE
combining commands with && fails

### ISSUE THREAD

**Issue by btknorr** [kimmobrunfeldt/chokidar-cli#6]
```node ../node_modules/chokidar-cli --initial '**/*' -c 'echo hello && echo goodbye'```

results in:

```hello [object Object] echo goodbye```

but should result in:

```
hello
goodbye
```

**Comment by btknorr** [comment]
looking at the code, you could use ```require('child_process').exec``` instead of spawn.

**Comment by kimmobrunfeldt** [comment]
With .exec it's not possible to print output of long running commands. I'm not sure how to fix this. Any ideas?

**Comment by btknorr** [comment]
actually what we ended up doing was just creating a .sh file with all the commands we needed, then use -c to call the .sh file.  this works well.  might be worth suggesting this in the readme.

**Comment by es128** [comment]
Would add lots of complexity, but perhaps split on `&`/`&&` and control the execution of the different commands on your own.

Or perhaps just detect the `&`/`&&` and switch to `exec` in that case - accepting the bit of degradation with how the process output prints.

**Comment by kimmobrunfeldt** [comment]
I wouldn't like to deal with all of these shell features myself, if there's a library which handles these I'm happy to start using that. But otherwise, I would recommend to do a bash script which executes the wanted command

**Comment by jgoux** [comment]
I use npm scripts to register my combined commands : 
```
"scripts": {
  "hello-goodbye": "echo hello && echo goodbye",
  "start": "chokidar --initial '**/*' -c 'npm run hello-goodbye'"
}
```
Then you just have to use `npm start`

**Comment by es128** [comment]
Thanks @jgoux - either that or a shell script will be the recommended methods for handling this situation. 

@kimmobrunfeldt maybe you can mention it in the readme.

In the meantime, closing this issue.

**Comment by kimmobrunfeldt** [comment]
In the newest release 1.0.1, all commands are passed to your system's shell. That should fix this problem too, assuming you have a shell which supports `&&`.
