### ISSUE TITLE
npm audit reports issue for lodash dependency

### ISSUE THREAD

**Issue by vpzomtrrfrt** [kimmobrunfeldt/chokidar-cli#64]
Running `npm audit` on this project shows a moderate vulnerability for lodash < 4.17.11 (https://npmjs.com/advisories/782)

**Comment by francisl** [comment]
that PR solved the issue, but for some reason (outdated) it was closed

https://github.com/kimmobrunfeldt/chokidar-cli/pull/58

**Comment by heikkipora** [comment]
This is a newer vulnerability (than that related to the PR originally). Let me fix this today

**Comment by heikkipora** [comment]
And it's out as v1.2.2
