### ISSUE TITLE
High severity security advisiory for lodash < 4.17.12

### ISSUE THREAD

**Issue by zr-ari** [kimmobrunfeldt/chokidar-cli#66]
https://nodesecurity.io/advisories/1065

It looks like there are a few closed issues related to updating this library, but since this is a new vulnerability, I figured it would be best to open a new issue. It seems like the fix will be as simple as bumping the version, and allowing for a range of patch versions might be helpful for avoiding the need to keep up with this every few months (`^4.17.12`).

**Comment by adit-hotstar** [comment]
This could have easily been avoided by adding a caret (`^`) or even a tilde (`~`) to the beginning of each dependency version number.

https://github.com/kimmobrunfeldt/chokidar-cli/blob/00aee901e41673e85ab5183d4e58eacafec5c983/package.json#L32-L40

Not doing so prevents npm from downloading the latest minor or patch versions. I did some digging around and I found that the carets were intentionally removed in the following commit.

https://github.com/kimmobrunfeldt/chokidar-cli/commit/d763a42306168c833a2f48deb9208dd39e465810#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Unfortunately, it seems like this repository is no longer being maintained.

**Comment by heikkipora** [comment]
True, this project is on quite low maintenance but dependency updates like this are still done :-)

**Comment by heikkipora** [comment]
v1.2.3 npm is out

**Comment by zr-ari** [comment]
Thanks @heikkipora !
