### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by wintercounter** [kimmobrunfeldt/chokidar-cli#69]
I'd like to know what breaking changes are being introduced in 2.0.0.

**Comment by heikkipora** [comment]
https://github.com/kimmobrunfeldt/chokidar-cli/releases/tag/2.0.0

Requires node.js v8.0.0 or newer as chokidar requires that as well as of v3+

**Comment by wintercounter** [comment]
I'm sorry, sometimes I'm checking the top menu for the releases page.
