### ISSUE TITLE
quiet/silent mode

### ISSUE THREAD

**Issue by jgoux** [kimmobrunfeldt/chokidar-cli#7]
Hi,
would it be possible to integrate a silent mode so there is no "change:path/to/file" output ?

**Comment by kimmobrunfeldt** [comment]
Yeah that's possible. What do you mean by silent? 

I was thinking that the silent option would only silence chokidar-cli's output, but the executed command would still output to stdout. What do you think?

**Comment by kimmobrunfeldt** [comment]
There's now implemented a `--silent` switch and commited to master.

**Comment by jgoux** [comment]
Yes this is exactly what I wanted !
I use chokidar to rebuild and run my haskell project, now I'll just have the app's output without any noise.
Thanks, it was fast ! :D

**Comment by kimmobrunfeldt** [comment]
Ok great! It's now released in 1.0.0 version. I bumped to major 1 to start following the semver correctly.
